[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "password_generator"
version = "0.1.0"
description = "A password generator project"
requires-python = ">=3.13"
dependencies = []

[project.optional-dependencies]
dev = [
    "pytest>=9.1.1",
    "flake8>=7.3.0",
]
